### ISSUE TITLE
Unable to verify Signature

### ISSUE THREAD

**Issue by tommmoe** [ankurk91/laravel-paypal-webhooks#1]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Laravel version : 10.45.1
* php version : 8.2.18

**Current behavior**
Unable to verify the signature of incoming PayPal webhook requests

**Expected behavior**
Webhook signatures will be matched and accepted

**Minimal reproduction of the problem with instructions**
I'll start off here by saying that I use spatie/laravel-stripe-webhooks as well and have no issues with that or verifying signatures in it.

- I'm unable to get the signature verified and get `The signature is invalid. 
```
{"exception":"[object] (Spatie\\WebhookClient\\Exceptions\\InvalidWebhookSignature(code: 0): The signature is invalid. at /var/www/html/vendor/spatie/laravel-webhook-client/src/Exceptions/InvalidWebhookSignature.php:11)
```
with '`verify_signature' => (bool) env('PAYPAL_SIGNATURE_VERIFY', true),` set to true, with it set to false, there's no issue.
- I've set the `PAYPAL_WEBHOOK_ID` env variable to the ID that was generated (and have tried to delete, get a new NGROK url and repeat the process) - same issue.
- I do have a custom signature_validator in my stripe-webhooks config, but I've disabled it from the config and still see the same issue.

Assuming that my issue is related to the package clash

**Comment by ankurk91** [comment]
I dont know how to help you in this. I can assure you that there is no package clash

**Comment by tommmoe** [comment]
Looks like it's working now, absolutely no clue what happened there, I wasn't even seeing webhook requests on the Paypal portal, but now it's all there.

Sorry to bother, thanks for the plugin!
